#!/bin/bash

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes



if [[ $TERM_PROGRAM == "WarpTerminal" ]]; then
   ZSH_THEME=""

else
   ZSH_THEME="spaceship"

   SPACESHIP_PROMPT_ORDER=(
      user          # Use,rname section
      venv          # venv
      dir           # Current directory section
      host          # Hostname section
      git           # Git section (git_branch + git_status)
      hg            # Mercurial section (hg_branch  + hg_status)
      exec_time     # Execution time
      line_sep      # Line break
      jobs          # Background jobs indicator
      exit_code     # Exit code section
      char          # Prompt character
   )

   SPACESHIP_PROMPT_ADD_NEWLINE=true

   SPACESHIP_USER_SHOW=always

   SPACESHIP_CHAR_SYMBOL="❯"
   SPACESHIP_CHAR_SUFFIX=" "

   SPACESHIP_DIR_TRUNC=0

   SPACESHIP_VENV_SHOW=true
   SPACESHIP_VENV_GENERIC_NAMES=false
   SPACESHIP_VENV_COLOR="blue"
   SPACESHIP_VENV_PREFIX="["
   SPACESHIP_VENV_SUFFIX="] "
   SPACESHIP_VENV_SYMBOL=""
fi
