#!/bin/bash

# LOAD USING ZINIT
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

zinit light zdharma/fast-syntax-highlighting
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-completions
# zinit light Aloxaf/fzf-tab



# LOAD USING OH-MY-ZSH
plugins=(
    git 
    vscode 
    docker 
    docker-compose 
    vscode
    history 
    kubectl  
    kubectx 
    python 
    pyenv 
    virtualenv
    poetry
    poetry-env
    pip
    gcloud
    azure
    aws
    golang
    gradle
    postgres
    sdk
    ubuntu
)
