#!/bin/bash

### START PYENV
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init -)"
if command -v pyenv >/dev/null 2>&1; then
    eval "$(pyenv init -)"
else
    echo "[WARN] pyenv não encontrado. Pulei inicialização do PYENV."
fi

# Python 3.10.5 /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
# Python 3.10.5 /usr/local/bin/python3
# Python 3.9.16 /opt/homebre/bin/python3.9
# Python 3.9.6  /usr/bin/python3

alias py='python3'
alias python='python3'

py-env-delete() {
    pyenv virtualenv-delete "$1"
}

py-env-create() {
    pyenv virtualenv "$1" "$2"
}

alias pip-clear='pip uninstall -y -r <(pip freeze)'

alias pip-list='pip list'
